In [ ]:
# 直接导入Python的内置基础数学库
import math
print(math.cos(math.pi))
# 从math中导入cos函数和pi变量
from math import cos, pi
print(cos(pi))
# 如果是个模块，在导入的时候可以起个别名，避免名字冲突或是方便懒得打字的人使用
import math as m
print(m.cos(m.pi))
# 从math中导入所有东西
from math import *
print(cos(pi))
print(dir())

In [ ]:
a = 'Life is short, you need Python'
a.lower()              	# 'life is short, you need Python'
help(str.lower)
a.upper()               	# 'LIFE IS SHORT, YOU NEED PYTHON'
a.count('i')            	# 2
a.find('e')             	# 从左向右查找'e'，3
a.rfind('need')         	# 从右向左查找'need'，19
a.replace('you', 'I')   # 'Life is short, I need Python'
tokens = a.split()    	# ['Life', 'is', 'short,', 'you', 'need', 'Python']
b = ' '.join(tokens)	# 用指定分隔符按顺序把字符串列表组合成新字符串
c = a + '\n'            	# 加了换行符，注意+用法是字符串作为序列的用法
c.rstrip()              	# 右侧去除换行符
[x for x in a]          	# 遍历每个字符并生成由所有字符按顺序构成的列表
'Python' in a   			# True

In [ ]:
a = list((1, 2, 3, 4))
a.pop()             # 把最后一个值4从列表中移除并作为pop的返回值
a.append(5)         # 末尾插入值，[1, 2, 3, 5]
a.index(2)          # 找到第一个2所在的位置，也就是1
a[2]                # 取下标，也就是位置在2的值，也就是第三个值3
a += [4, 3, 2]      # 拼接，[1, 2, 3, 5, 4, 3, 2]
a.insert(1, 0)      # 在下标为1处插入元素0，[1, 0, 2, 3, 5, 4, 3, 2]
a.remove(2)         # 移除第一个2，[1, 0, 3, 5, 4, 3, 2]
a.reverse()         # 倒序，a变为[2, 3, 4, 5, 3, 0, 1]
a[3] = 9            # 指定下标处赋值，[2, 3, 4, 9, 3, 0, 1]
b = a[2:5]          # 取下标2开始到5之前的子序列，[4, 9, 3]
c = a[2:-2]         # 下标也可以倒着数，方便算不过来的人，[4, 9, 3]
d = a[2:]           # 取下标2开始到结尾的子序列，[4, 9, 3, 0, 1]
e = a[:5]           # 取开始到下标5之前的子序列，[2, 3, 4, 9, 3]
f = a[:]            # 取从开头到最后的整个子序列，相当于值拷贝，[2, 3, 4, 9, 3, 0, 1]
a[2:-2] = [1, 2, 3]  # 赋值也可以按照一段来，[2, 3, 1, 2, 3, 0, 1]
g = a[::-1]	    # 也是倒序，通过slicing实现并赋值，效率略低于reverse()
a.sort()
print(a)            # 列表内排序，a变为[0, 1, 1, 2, 2, 3, 3]

In [ ]:
# random
import random
#a = range(10) range not support
a = list(range(10))                 # 生成一个列表，从0开始+1递增到9
print(a)                      # [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
random.shuffle(a)             # shuffle函数可以对可遍历且可变结构打乱顺序
print(a)                      # [4, 3, 8, 9, 0, 6, 2, 7, 5, 1]
b = sorted(a)                 #  排序，默认升序
print(b)                      # [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
c = sorted(a, reverse=True)
print(c)                      # [9, 8, 7, 6, 5, 4, 3, 2, 1, 0]

In [ ]:
# set
A = set([1, 2, 3, 4])
B = {3, 4, 5, 6}
C = set([1, 1, 2, 2, 2, 3, 3, 3, 3])
print(C)        # 集合的去重效果，set([1, 2, 3])
print(A | B)    # 求并集，set([1, 2, 3, 4, 5, 6])
print(A & B)    # 求交集，set([3, 4])
print(A - B)    # 求差集，属于A但不属于B的，set([1, 2])
print(B - A)    # 求差集，属于B但不属于A的，set([5, 6])
print(A ^ B)    # 求对称差集，相当于(A-B)|(B-A)，set([1, 2, 5, 6])

In [ ]:
# dict
a = {'Tom': 8, 'Jerry': 7}
print(a['Tom'])             # 8
b = dict(Tom=8, Jerry=7)    # 一种字符串作为键更方便的初始化方式
print(b['Tom'])             # 8
if 'Jerry' in a:            # 判断'Jerry'是否在keys里面
    print(a['Jerry'])        # 7
print(a.get('Spike'))       # None，通过get获得值，即使键不存在也不会报异常
a['Spike'] = 10
a['Tyke'] = 3
a.update({'Tuffy': 2, 'Mammy Two Shoes': 42})
print(a.values())   # dict_values([8, 2, 3, 7, 10, 42])
print(a.pop('Mammy Two Shoes'))     # 移除'Mammy Two Shoes'的键值对，并返回42
print(a.keys())     # dict_keys(['Tom', 'Tuffy', 'Tyke', 'Jerry', 'Spike']) 

# 输出 k,v
for k, v in a.items():
    print("k = {}, v = {}".format(k,v))

# 按照 insert 顺序排列的 dict 
from collections import OrderedDict
a = {1: 2, 3: 4, 5: 6, 7: 8, 9: 10}
b = OrderedDict({1: 2, 3: 4, 5: 6, 7: 8, 9: 10})
print(a)    # {1: 2, 3: 4, 9: 10, 5: 6, 7: 8}
print(b) 

In [ ]:
# file io
import numpy as np
with open('name_age.txt', 'w') as f: 	# 打开文件，写入模式 write
    string = """xiaoyang
xiaowu
qiqi
zhangyuxin"""
    # 3个双引号会使得之间的内容都成为 str 类型
    print(string)
    f.write(string) # 将这几行都写入文件
    
with open('name_age.txt', 'r') as f: 	# 打开文件，读取模式
    print("open file name_age.txt")
    lines = f.readlines()              	# 一次读取所有行
    for i, line in enumerate(lines):                  	# 按行格式化并显示信息
        l = line[:-1]           # 去掉末尾的换行符
        print(i, l)
        #print('{} is {} years old.'.format(name, age))

In [ ]:
# numpy
import numpy as np
a = [1, 2, 3, 4]     	#
b = np.array(a)         	# array([1, 2, 3, 4])
type(b)                         	# <type 'numpy.ndarray'>
print(b, type(b))
print(b.shape)                   	# (4,)
print(b.argmax())               	# 3
print(b.max())                  	# 4
print(b.mean())                 	# 2.5
print("二维数组")
c = [[1, 2], [3, 4]]  	# 二维列表
d = np.array(c)         	# 二维numpy数组
print(d.shape)                   	# (2, 2)
print(d.size)                   	# 4
print(d.max(axis=0))            	# 找维度0，也就是最后一个维度上的最大值，array([3, 4])
print(d.max(axis=1))            	# 找维度1，也就是倒数第二个维度上的最大值，array([2, 4])
print(d.mean(axis=0))          	# 找维度0，也就是第一个维度上的均值，array([ 2.,  3.])
print(d.flatten())              	# 展开一个numpy数组为1维数组，array([1, 2, 3, 4])
print(np.ravel(c))               # 展开一个可以解析的结构为1维数组，array([1, 2, 3, 4])
print("三维矩阵")
# 3x3的浮点型2维数组，并且初始化所有元素值为1
e = np.ones((3, 3), dtype=np.float32)
print(e, e.dtype)
# 创建一个一维数组，元素值是把3重复4次，array([3, 3, 3, 3])
f = np.repeat((2,2),3)
print("2 * 2 矩阵， value = 3", f, f.shape, f.size,f.dtype)
# 2x2x3的无符号8位整型3维数组，并且初始化所有元素值为0
g = np.zeros((2,3), dtype=np.uint8)
print(g.shape,type(g.shape), g, g.size, g.dtype)                    # (2, 2, 3)
g = g.astype(np.float64)  # 用另一种类型表示
print(g.shape,type(g.shape), g, g.size, g.dtype)  
l = np.arange(10)      	# 类似range，array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
m = np.linspace(0, 6, 5)  # 等差数列，0到6之间5个取值，array([ 0., 1.5, 3., 4.5, 6.])
p = np.array(
    [[1, 2, 3, 4],
     [5, 6, 7, 8]]
)
# np.save('p.npy', p)     # 保存到文件
q = np.load('p.npy')    # 从文件读取
print(q,q.dtype)

In [ ]:
import numpy as np
# 绝对值，1
a = np.abs(-1)
print(a, type(a))
# sin函数，1.0
b = np.sin(np.pi/2)
# tanh逆函数，0.50000107157840523
c = np.arctanh(0.462118)
# e为底的指数函数，20.085536923187668
d = np.exp(3)
# 2的3次方，8
f = np.power(2, 3)
# 点积，1*3+2*4=11
g = np.dot([1, 2], [3, 4])
# 开方，5
h = np.sqrt(25)
# 求和，10
l = np.sum([1, 2, 3, 4])
# 平均值，5.5
m = np.mean([4, 5, 6, 7])
# 标准差，0.96824583655185426
p = np.std([1, 2, 3, 2, 1, 3, 2, 0])

In [63]:
# castboard
import numpy as np
import os, sys
def line():
    return sys._getframe().f_lineno
arr1 = np.arange(1,10)
print(arr1)
import numpy.random as random
print(random.random((3, 3)))
cout(random.sample((3, 3)))
print(random.random_sample((3, 3)))
print(line(), random.ranf((3, 3)))

# 产生10个[1,6)之间的浮点型随机数
5*random.random(10) + 1
random.uniform(1, 6, 10)
# 产生10个[1,6)之间的整型随机数
random.randint(1, 6, 10)
# 产生2x5的标准正态分布样本
random.normal(size=(5, 2))
# 产生5个，n=5，p=0.5的二项分布样本
random.binomial(n=5, p=0.5, size=5)
a = np.arange(10)
# 从a中有回放的随机采样7个
random.choice(a, 7)
# 从a中无回放的随机采样7个
random.choice(a, 7, replace=False)
# 对a进行乱序并返回一个新的array
b = random.permutation(a)
# 对a进行in-place乱序
random.shuffle(a)
# 生成一个长度为9的随机bytes序列并作为str返回
# '\x96\x9d\xd1?\xe6\x18\xbb\x9a\xec'
random.bytes(9)

[1 2 3 4 5 6 7 8 9]
[[0.08630745 0.04479364 0.67666601]
 [0.96871766 0.4258366  0.10963172]
 [0.78029236 0.32914432 0.95376133]]
 line : 4 --> [[0.07004227 0.98511995 0.41427855]
 [0.22386956 0.96840269 0.80109811]
 [0.88457847 0.94487981 0.56748535]].
[[0.57715064 0.83551316 0.2518465 ]
 [0.33921765 0.90591102 0.24133535]
 [0.29053482 0.2046455  0.59424887]]
5 [[0.91815491 0.46585643 0.18975191]
 [0.72693905 0.01935802 0.88374481]
 [0.42379569 0.33240952 0.7581293 ]]


b'\xb5Q,\xc6\xf5\xf5A\xcb\t'